<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 *
 * @category  Amadeco
 * @package   Amadeco_SmileCustomEntityLayeredNavigation
 * @copyright Copyright (c) Amadeco (https://www.amadeco.fr) - Ilan Parmentier
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

/** @var \Amadeco\SmileCustomEntityLayeredNavigation\Block\SetList $block */
/** @var \Magento\Framework\Escaper $escaper */

$entityCollection = $block->getLoadedEntityCollection();
?>
<?php if (!$entityCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $viewMode = $block->getMode();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var \Magento\Eav\Api\Data\AttributeSetInterface $entity */ ?>
            <?php foreach ($entityCollection as $entity) : ?>
                <li class="item product product-item">
                    <?= $block->getParentBlock()->getEntityHtml($entity) ?>
                </li>
            <?php endforeach ?>
        </ol>
    </div>

    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
<?php endif ?>
